name: deploy
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
        - shell: bash
        - uses: actions/checkout@v2
        - name: decrypt_settings
          run: |
           for filename in ./settings/*; do
            gpg --quiet --batch --yes --decrypt --passphrase="$SETTINS_DECRYPT_KEY" --output "./settings/${$filename/.gpg/}" "$filename"
           done
        - name: containerize  
        - env:
            APP_NAME: ${{ vars.APP_NAME }}
            PORT: ${{ secrets.PORT }}
            FLASK_APP: ${{ vars.FLASK_APP }}
            FLASK_ENV: ${{ vars.FLASK_ENV }}
            MONGODB_URL: ${{ secrets.MONGODB_URL }}
            MONGODB_DB: ${{ secrets.MONGODB_DB }}
            SESSION_TYPE: ${{ vars.SESSION_TYPE }}
            REDIS_URL: ${{ secrets.REDIS_URL }}
            REDIS_QUEUE_NAME: ${{ secrets.REDIS_QUEUE_NAME }} 
          run: |
           docker build --build-arg PORT="$PORT"  --build-arg  FLASK_APP="$FLASK_APP" --build-arg  FLASK_ENV="$FLASK_ENV" --build-arg  MONGODB_URL="$MONGODB_URL" --build-arg MONGODB_DB="$MONGODB_DB" --build-arg MONGODB_AUTH_MECHANISM=DEFAULT --build-arg SESSION_TYPE="$SESSION_TYPE"  --build-arg REDIS_URL="$REDIS_URL" --build-arg  REDIS_QUEUE_NAME="REDIS_QUEUE_NAME"  -t  $APP_NAME .
       